config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions:"users/sessions", registrations: "users/registrations" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'download', controller:'application', action:'download'
  get 'delete', controller:'application', action:'delete'
  post 'post_test', controller:'application', action:'post_test'
  get 'err', controller:'application', action:'err'
  get 'privacy_policy', controller: 'home', action: 'privacy_policy'
  post 'cancel_fb_authorization', controller: 'application', action: 'dev_cancel_fb'
  get 'google3e784468cd0fd9bb.html', controller: 'home', action: 'domain_auth'
  scope :controller=>"home",:path=>"/", :as=>"home" do
    get '/'=>:home
    get 'index'=>:index
    get 'about'=>:about
    get 'yeah'=>:yeah
    get 'test'=>:test
    post 'webhook'=>:webhook
  end

  resources :accounts, controller: 'accounts' do
    collection do
      get :index
      get :new
      post :add
      get :all
      get :show_day
      post :delete
      get :report
    end
  end

  resources :to_do_lists do
    resources :to_do_items do
      member do
        post :update_position
      end
    end
  end

  scope :controller => "excel", :path => "/excel", :as => "excel" do
    # get 'meetings/:id' => :show, :as => "meeting"
    get '/' => :index
    post '/upload' => :upload
    get '/show_csv' => :show_csv
    get '/processed_csv' => :processed_csv
    get '/export_filter_africa' => :export_filter_africa
  end

  scope :controller => "line", :path=> "/line", :as=>"line" do
    post '/webhook' => :webhook
  end

  resources :supplies, :controller=>'supplies' do
    collection do
      get '/all' => :all
    end
  end

  resources :articles do
    collection do
      get :search, to: redirect("/")
      post :search
      get :backup_settings
      post :backup
      get :mine
      post :preview_markdown
      get :hot
      get :cached_hot
      get :get_link_title
    end
    member do
      put :update_state
    end
  end

  resources :words, :controller=>'words'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/shared/_alert.html.erb
<script>
  function foldAlert(this_obj){
    console.log("Reversing...")
    setTimeout( ()=>{
       this_obj.style.animation = "alert-backwards 1s forwards running";
    }, 3000);
  }
</script>
<% if notice %>
  <p class="alert alert-success" onanimationend="foldAlert(this)">
   <span class="alert-txt" id="alert-txt"><%= notice %></span>
  </p>
<% end %>
<% if alert %>
   <p class="alert alert-danger" onanimationend="foldAlert(this)">
   <span class="alert-txt" id="alert-txt"> <%= alert %></span>
  </p>
<% end %>

app/views/shared/_footer.html.erb
<%= stylesheet_link_tag "footer" %>
<footer>
  <div class="block">
    <h2>About</h2>
    <ul>
      <li><%= link_to "Me", ENV['ABOUT_URL'] || "javascript:void(0)" %></li>
      <li><a href="https://github.com/kylemocode/BESG">Back End Study Group</a></li>
    </ul>
  </div>
  <div class="block">
    <h2>Connect</h2>
    <ul>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Updates</a></li>
    </ul>
  </div>
  <div class="block">
    <h2>Resources</h2>
    <ul>
      <li><%= link_to t('navbar.color_picker'), ENV['COLORPICKER_URL'] || "javascript:void(0)"%></li>
      <li><%= link_to t('navbar.word_book'), words_path%></li>
    </ul>
  </div>
  <ul class="contact-links">
    <li><a href="<%= ENV['MEDIUM_URL'] %>"><%= image_tag("ros/medium_subed_logo.png") %></li>
    <li><a href="<%= ENV['GITHUB_URL'] %>"><%= image_tag("ros/git_subed_logo.png") %></li>
    <li><a href="javascript:void(0)"><%= image_tag("ros/fb_subed_logo.png") %></li>
    <li><a href="<%= ENV['LINKEDIN_URL'] %>"><%= image_tag("ros/linkedin_subed_logo.png") %></li>
  </ul>
  <ul class="others">
    <li><a href="javascript:void(0)">Terms Of Use</a></li>
    <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
    <li><a href="javascript:void(0)">Cookie Policy</a></li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag "header" %>
<header>
  <a href="/"><%= image_tag("ros/ruby-on-stimulants1772x757.png") %></a>
  <%= form_tag search_articles_path, class: 'search-form' do%>
    <%= text_field_tag :keyword, nil, autocomplete: 'off', placeholder: t('controller.articles.search'), disabled: true %>
  <% end %>
  <ul>
    <li>
      <div onclick="toggleSearchBar()">
        <%= svg_asset('search-icon') %>
      </div>
    </li>
    <li>
      <div onclick="toggleSideNav()">
        <%= svg_asset('menu-icon') %>
      </div>
    </li>
  </ul>
  <div class="wrap-alert" id="wrap-alert">
    <% if notice %>
      <p class="alert alert-success " onanimationend="foldAlert(this)">
       <span class="alert-txt"><%= notice %></span>
      </p>
    <% end %>
    <% if alert %>
       <p class="alert alert-danger " onanimationend="foldAlert(this)">
       <span class="alert-txt"> <%= alert %></span>
      </p>
    <% end %>
  </div>
</header>
<nav class="nav-side">
  <% if current_user %>
    <div>
      <h2>
        <img src="<%= current_user.image_url%>" alt="img" class="profile-image">
        <span><%= username(current_user) %></span>
      </h2>
      <hr>
      <ul>
        <li><%= link_to "<span class=\"pen\">&#x270e;</span> #{t('controller.articles.write_new')}".html_safe, new_article_path, class: " " %></li>
        <li><%= link_to t('controller.articles.mine').html_safe, mine_articles_path, class: " " %></li>
          <% if current_user.premium? %>
            <li><%= link_to t('controller.articles.backup').html_safe, backup_settings_articles_path, class: " " %></li>
          <% end %>
        <li><%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: " ", data: {confirm: t("devise.sessions.confirm_sign_out")} %></li>
      </div>
    </div>
  <% else %>
    <div>
      <h2>
        <div></div>
        <span><%= t('navbar.not_signed_in') %></span>
      </h2>
      <hr>
      <ul>
        <li><%= link_to t('navbar.sign_in'), new_user_session_path, class: " font signin" %></li>
        <li><%= link_to t('navbar.sign_up'), new_user_registration_path, class: " font signup" %></li>
      </ul>
    </div>
  <% end %>


  <div>
    <h2><%= t('navbar.explore') %></h2>
    <hr>
    <ul>
      <li><%= link_to t('navbar.articles'), articles_path, class: " " %></li>
      <li><%= link_to t('navbar.about'), home_about_path, class: " " %></li>
    </ul>
  </div>
  </nav>

app/views/shared/_nav.html.erb
<nav id="nav-top" class="notosans">
  <a class="link-wrap-title" href="/">
    <%= svg('ruby', class: "ruby-icon") %>
    <span class="title">RubyOnStimulants</span>
  </a>
  <%= form_tag search_articles_path, id: 'search-form' do%>
    <%= text_field_tag :keyword, nil, id: 'searchbar', autocomplete: 'off', placeholder: t('controller.articles.search'), disabled: true %>
  <% end %>
  <div class="nav-top-options-container">
    <div class="nav-top-option idle" id="nav-side-toggle" onclick="toggleSearchBar()">
      <%= svg_asset('search-icon') %>
    </div>
    <div id="nav-side-toggle" class="nav-top-option idle" onclick="toggleSideNav()">
      <%= svg_asset('menu-icon') %>
    </div>
  </div>
  <nav id="nav-side" class="no-dark">
    <div id="nav-side-menu-container">

      <% if current_user %>
        <div class="nav-side-block">
          <h2 class="nav-side-block-title font text-t3">
            <img src="<%= current_user.image_url%>" alt="img" class="nav-profile-img crop-circle">
            <span class="notosans username text-t2"><%= username(current_user) %></span>
          </h2>
          <hr class="nav-side-block-hr">
          <div class="nav-side-block-content-container">
            <h3 class="nav-side-block-content"><%= link_to "<span class=\"pen\">&#x270e;</span> #{t('controller.articles.write_new')}".html_safe, new_article_path, class: "text-t3 notosans" %></h3>
            <h3 class="nav-side-block-content"><%= link_to t('controller.articles.mine').html_safe, mine_articles_path, class: "text-t3 notosans" %></h3>
              <% if current_user.premium? %>
                <h3 class="nav-side-block-content"><%= link_to t('controller.articles.backup').html_safe, backup_settings_articles_path, class: "text-t3 notosans" %></h3>
              <% end %>
            <h3 class="nav-side-block-content"><%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: "text-t3 notosans", data: {confirm: t("devise.sessions.confirm_sign_out")} %></h3>
          </div>
        </div>
      <% else %>
        <div class="nav-side-block">
          <h2 class="nav-side-block-title font text-t3">
            <div class="nav-profile-img crop-circle" style="background-color: #585858;"></div>
            <span class="notosans username text-t4"><%= t('navbar.not_signed_in') %></span>
          </h2>
          <hr class="nav-side-block-hr">
          <div class="nav-side-block-content-container">
            <h3 class="nav-side-block-content"><%= link_to t('navbar.sign_in'), new_user_session_path, class: "text-t3 font signin" %></h3>
            <h3 class="nav-side-block-content"><%= link_to t('navbar.sign_up'), new_user_registration_path, class: "text-t3 font signup" %></h3>
          </div>
        </div>
      <% end %>


      <div class="nav-side-block">
        <h2 class="nav-side-block-title font text-t5"><%= link_to t('navbar.explore'), home_news_path, class: "notosans text-t3" %></h2>
        <hr class="nav-side-block-hr">
        <div class="nav-side-block-content-container">
          <h3 class="nav-side-block-content"><%= link_to t('navbar.articles'), articles_path, class: "notosans text-t3" %></h3>
          <h3 class="nav-side-block-content"><%= link_to t('navbar.color_picker'), ENV['COLORPICKER_URL'] || "javascript:void(0)", class: "notosans text-t3" %></h3>
          <h3 class="nav-side-block-content"><%= link_to t('navbar.word_book'), words_path, class: "notosans text-t3"%></h3>
          <h3 class="nav-side-block-content"><%= link_to t('navbar.to_do_list'), to_do_lists_path, class: "notosans text-t3"%></h3>
          <h3 class="nav-side-block-content"><%= link_to t('navbar.about'), ENV['ABOUT_URL'] || "javascript:void(0)", class: "notosans text-t3" %></h3>
        </div>
      </div>
    </div>
  </nav>
</nav>

app/views/shared/_rails_among_us.html.erb
<%= stylesheet_link_tag "among_us" %>
<%= javascript_include_tag "among_us" %>

<div class="space-wrapper">
  <div class="player-ruby-wrap">
    <%= image_tag("ruby-big.svg", id: "player-ruby") %>
  </div>
  <div id="narration" class="paragraph text-t2"></div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar" class="notosans">
  <div class="sidebar__block-container" id="latest-articles-container">
    <h3 class="block-title text-t4"><%= t('sidebar.you_might_interested') %></h3>
    <hr class="block-hr">
    <div class="block-content-container">
      <%= link_to "Dokku - 用heroku的方式部署到你的EC2 !", article_path(id: 1), class: "block-content-link font text-dft" %>
      <%= link_to "Rails: Gutentag tag_names N+1 problem", article_path(id: 43), class: "block-content-link font text-dft" %>
    </div>
  </div>
  <div class="sidebar__block-container" id="about-website">
    <h3 class="block-title text-t4"><%= t('sidebar.about_the_site') %></h3>
    <hr class="block-hr">
    <p class="block-content text-t4"><%= t('sidebar.about_site') %></p>
  </div>
</div>

app/views/shared/_skiers.html.erb
<%= javascript_include_tag 'moonNstars/moonNstars', 'data-turbolinks-track': 'reload' %>
<%= image_tag('moon.png',id:'moon') %>
<% 5.times.each do |i|%>
  <%= image_tag('star.png',id:"star-"+i.to_s) %>
<% end %>

app/views/shared/error.html.erb
<%= stylesheet_link_tag('error') %>
<div class="container font text-dft error">
  <h1 class="error-title"><%= @i18n_message %></h1>
  <% if current_user && current_user.admin? %>
    <h2 class="error-subtitle"><%= @error_message %></h2>
  <% end %>
  <%= link_to(t('controller.general.go_home'), root_path, class: "link-go-home font text-dft") %>
</div>

app/views/shared/result.html.erb
<%= stylesheet_link_tag('result') %>
<main>
  <div class="wrap-result">
    <h1 class="txt"><%= @success ? "Success" : "Error"  %> <%= @status %></h1>
      <h2 class="subtitle"><%= t("controller.general.#{@success ? "success" : "error" }") %></h2>
      <% if @data.presence %>
        <h4 class="txt"> <%= @data%> </h4>
      <% end %>
      <p class="wrap-message txt error"><%= @message %></p>
      <%= link_to(t('controller.general.go_home'), root_path) %>
  </div>
</main>