config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions:"users/sessions", registrations: "users/registrations" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'download', controller:'application', action:'download'
  get 'delete', controller:'application', action:'delete'
  post 'post_test', controller:'application', action:'post_test'
  get 'err', controller:'application', action:'err'
  get 'privacy_policy', controller: 'home', action: 'privacy_policy'
  post 'cancel_fb_authorization', controller: 'application', action: 'dev_cancel_fb'
  get 'google3e784468cd0fd9bb.html', controller: 'home', action: 'domain_auth'
  scope :controller=>"home",:path=>"/", :as=>"home" do
    get '/'=>:home
    get 'index'=>:index
    get 'about'=>:about
    get 'yeah'=>:yeah
    get 'test'=>:test
    post 'webhook'=>:webhook
  end

  resources :accounts, controller: 'accounts' do
    collection do
      get :index
      get :new
      post :add
      get :all
      get :show_day
      post :delete
      get :report
    end
  end

  resources :to_do_lists do
    resources :to_do_items do
      member do
        post :update_position
      end
    end
  end

  scope :controller => "excel", :path => "/excel", :as => "excel" do
    # get 'meetings/:id' => :show, :as => "meeting"
    get '/' => :index
    post '/upload' => :upload
    get '/show_csv' => :show_csv
    get '/processed_csv' => :processed_csv
    get '/export_filter_africa' => :export_filter_africa
  end

  scope :controller => "line", :path=> "/line", :as=>"line" do
    post '/webhook' => :webhook
  end

  resources :supplies, :controller=>'supplies' do
    collection do
      get '/all' => :all
    end
  end

  resources :articles do
    collection do
      get :search, to: redirect("/")
      post :search
      get :backup_settings
      post :backup
      get :mine
      post :preview_markdown
      get :hot
      get :cached_hot
      get :get_link_title
    end
    member do
      put :update_state
    end
  end

  resources :words, :controller=>'words'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery with: :null_session
  layout false
  def index
  end

  def home
  end

  def news
    @news_list = news_list
  end

  def yeah
  end

  def domain_auth
    @htmldoc = File.read('google3e784468cd0fd9bb.html.txt')
    render html: @htmldoc
  end

  def webhook
    return render json:{message:"webhook"}, status: :ok
  end

  def privacy_policy
  end

  private
  def news_list
    [
      {
        title: "Rename site to ActiveMine and implement new theme layout and style",
        description: "took me 3 days",
        date: "Nov 15, 2020"
      },
      {
        title: "Reanimate To do list",
        description: "fix a lot of logic for to do list",
        date: "Nov 1, 2020"
      },
      {
        title: "Introduce Rspec for to do list/items",
        description: "feat: install rspec",
        date: "Oct 29, 2020"
      },
      {
        title: "Switch category field to tags for articles",
        description: "feat: gutentag",
        date: "Oct 26, 2020"
      },
      {
        title: "Working todolist version1 with SJR",
        description: "feat: using SJR",
        date: "Oct 26, 2020"
      },
      {
        title: "Add new todo list animation",
        description: "feat: replot animation",
        date: "Oct 26, 2020"
      },
      {
        title: "Adjust article container structure",
        description: "feat: adjust article container",
        date: "Oct 25, 2020"
      },
      {
        title: "Implement to do list mockup into rails",
        description: "feat: view, controller, routes, blablabla...",
        date: "Oct 25, 2020"
      },
      {
        title: "Add jQuery in to do list mockup",
        description: "feat: jquery ui",
        date: "Oct 24, 2020"
      },
      {
        title: "Finish working to do list prototype",
        description: "feat: pure html/css/javascript",
        date: "Oct 24, 2020"
      },
      {
        title: "Recreate To-do list, update markdown parser helper",
        description: "feat: drop and create with new fields",
        date: "Oct 23, 2020"
      },
      {
        title: "Add private state for article, update UI state style",
        description: "feat: Update state in articles new and edit",
        date: "Oct 18, 2020"
      },
      {
        title: "Add private state for article, update UI state style",
        description: "feat: Update state in articles new and edit",
        date: "Oct 18, 2020"
      },
      {
        title: "Set \"order by\" in articles index",
        description: "feat: order article by id desc",
        date: "Oct 14, 2020"
      },
      {
        title: "Feature: Re-expose WordBook functionality",
        description: "feat: activate words again with new style",
        date: "Oct 14, 2020"
      },
      {
        title: "Switch from showing part of the content to subtitle",
        description: "feat: use subtitle in articles list",
        date: "Oct 14, 2020"
      },
      {
        title: "Feature: Expose ColorPicker",
        description: "feat: expose color picker, about me link",
        date: "Oct 8, 2020"
      },
      {
        title: "Markdown style and call method",
        description: "feat: generalize markdown, change pre inline code style",
        date: "Oct 1 ,2020"
      },
      {
        title: "Reset root path",
        description: "feat: make article#index as root path",
        date: "Oct 8, 2020"
      },
      {
        title: "hljs",
        description: "refactor: load hljs generally in layout",
        date: "Oct 8, 2020"
      },
      {
        title: "Update style",
        description: "feat: use noto sans light for pre/fix: hljs style in articles#new",
        date: "Oct 7, 2020"
      },
      {
        title: "Fix hjls not loading properly",
        description: "fix: hljs in articles#new",
        date: "Oct 7, 2020"
      },
      {
        title: "add hight in article show",
        description: "fix: article show hightlight",
        date: "Oct 4, 2020"
      },
      {
        title: "Change hljs style for code blocks",
        description: "feat: use tommorow night",
        date: "Oct 3, 2020"
      },
      {
        title: "Feature: add hljs to hightlight code blocks",
        description: "feat: add hightlight js, adjust style, add confirm leaving on edit page",
        date: "Oct 3, 2020"
      },
      {
        title: "Add confirm sign-out, and changed some style",
        description: "feat: redo some style, adjust style, add confirm sign-out",
        date: "Oct 3, 2020"
      },
      {
        title: "Remove fat fonts",
        description: "feat: remove cjktc font to reduce project size",
        date: "Sep 3,02020"
      },
     {
        title: "feat: Changed some styles",
        description: "Change container margin top to 0, and overflow scroll",
        date: "Oct 14, 2020"
      },
      {
        title: "feat: Changed some styles",
        description: "Change container margin top to 0, and overflow scroll",
        date: "Sep 2,62020"
      },
      {
        title: "feat: Markdown Preview for Articles",
        description: "Add markdown PREVIEW support in articles#edit/show",
        date: "Sep 2,02020"
      },
      {
        title: "Feat: Markdown Support for Articles",
        description: "Integrated redcarpet gem",
        date: "Sep 1,92020"
      },
      {
        title: "Feat: Article Edit Page",
        description: "Article edit page in rails",
        date: "Sep 1,82020"
      },
      {
        title: "Feat: Add article edit page mockup",
        description: "Dev using html/scss/js",
        date: "Sep 1,72020"
      },
      {
        title: "refactor: Stylesheets",
        description: "Rename some style files/css class names",
        date: "Sep 1,62020"
      },
      {
        title: "feat: Add article show page",
        description: "View/Controller",
        date: "Sep 1,52020"
      },
      {
        title: "feat: Create side nav bar",
        description: "As well as its transition using js",
        date: "Sep 14, 2020"
      },
      {
        title: "feat: Home page in rails",
        description: "Implement mockup into rails: home page",
        date: "Sep 1,32020"
      },
      {
        title: "Update: Mon, 05 Sep 2020",
        description: "Change all style into a new theme! Finally it’s here.",
        date: "Sep 0,52020"
      },
      {
        title: "feat: Add word card",
        description: "Model/View/Controller",
        date: "May 14, 2020"
      },
      {
        title: "New theme!",
        description: "Change all style into a new theme! Finally it’s here.",
        date: "Jan 19, 2020"
      },
      {
        title: "harrysworkspace",
        description: "Day of site creation.",
        date: "Oct 19, 2019"
      }
    ]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/animation_test.html.erb
<%= render("shared/skiers") %>

app/views/home/index.html.erb
<%= stylesheet_link_tag "home" %>
<div class="logo-wrap">
  <%= image_tag("ros/ruby-on-syringe415x590.png") %>
  <h1>Ruby On Stimulants</h1>
</div>
<h3>Learn and make things fun, like taking a stimulant</h3>
<ul>
  <li><a href="#">About</a></li>
  <li><%= link_to "Articles", articles_path %></li>
</ul>
<div class="icons-wrap">
  <a href="<%= ENV['MEDIUM_URL']%>"><%= image_tag("ros/medium_subed_logo.png", class: "icon") %></a>
  <a href="javascript:void(0)"><%= image_tag("ros/fb_subed_logo.png", class: "icon") %></a>
  <a href="<%= ENV['GITHUB_URL']%>"><%= image_tag("ros/git_subed_logo.png", class: "icon") %></a>
  <a href="<%= ENV['LINKEDIN_URL']%>"><%= image_tag("ros/linkedin_subed_logo.png", class: "icon") %></a>
</div>

app/views/home/list_home.html.erb
<div id="container-rw">
  <%= form_tag(post_list_path, method:'post') do %>
  <table class="txt table table-dark">
    <thead>
    <th scope="col">Ban</th>
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Gender</th>
    <th scope="col">Email</th>
    </thead>

    <tbody class="list">
      <div class="form-wrapper">
      <%@data.each do |d|%>
        <tr>
          <td> <%= check_box_tag("ban_user[]" ,d[:id],false)%></td>
          <td scope="row"><%=d[:id] %>  </td>
          <td scope="row"><%=d[:name] %>  </td>
          <td scope="row"><%=d[:gender] %>  </td>
          <td scope="row"><%=d[:email] %>  </td>
        </tr>
      <%end%>
      </div>
    </tbody>

  </table>

   <div class="lower_row">
       <%= submit_tag("Go",class:"btn-grad btn-secondary")%>
   </div>

   <%end%>

   </div>

app/views/home/news.html.erb
<%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload'%>

<div class="container">
  <p class="welcome-txt text-dft notosans">This website is managed by <a href="https://github.com/harryuan65/" class="text-dft notosans">Harry Yuan</a>.</p>
  <section class="news">
    <h1 class="block-title text-t2 notosans">Updates</h1>
    <hr class="block-hr">
    <div class="section-content-container">
     <% @news_list.each do |news| %>
      <div class="article-container">
        <a href="javascript:void(0)" class="article-link news">
         <h3 class="article-title font text-t3"><%= news[:title] %></h3>
         <span class="article-description font text-dft"><%= news[:description] %></span>
        </a>
        <span class="article-author font text-dft"></span>
        <span class="article-created-at font text-dft"><%= news[:date] %></span>
      </div>
     <% end %>
    </div>
  </section>
</div>

app/views/home/privacy_policy.html.erb
<div id="terms-container" class="container font text-t3">
  <div id="terms-content">
		<h1 class="title">RubyOnStimulants 隱私權政策</h1>
		<div class="section">
			<p>最後更新日期：2020/05/03</p>
			<p>RubyOnStimulants 服務（以下簡稱「RubyOnStimulants」、「本服務」和「本不是公司」）非常重視 RubyOnStimulants 的會員（以下簡稱「會員」、「您」或「您的」）的線上個人隱私。為了讓您瞭解我們將如何蒐集、應用及保護您所提供的個人資訊，請詳閱下列隱私權保護聲明。</p>
		</div>
		<h3>個人資料之取得：</h3>
		<ul>
			<li>Facebook/google登入僅最低限度登入</li>
			<li>絕對不會都拿你的資料去玩。</li>
		</ul>

		<h3>個人資料之運用：</h3>
		<p>您註冊會員時所輸入之資料，僅供本服務提供第三方登入使用
			<ol>
				<li>既然您已同意登入，就代表你同意讓我最低限度存取你的資料</li>
				<li>經您書面同意利用於其他目的。</li>
			</ol>
		</p>

		<h3>如何保護您的個人資料: </h3>
		<ul>
		  <li>我們使用256 SSL保護機制</li>
		  <li>不想逛了記得登出</li>
    </ul>

		<h3>其他資料之蒐集和運用:</h3>
		<ul>
			<li>本服務將依據使用者註冊、促銷活動或相關問卷調查所提供的資料，就放在那邊，也沒什麼資料可以玩。 凡未經您主動註冊所產生的資料，如使用者機器的 IP 位址、使用時間、使用的瀏覽器、瀏覽及點選紀錄等資料，本服務將針對必要提供之服務。不管皆不外漏給第三方非 Harry's Workspace 服務平台。</li>
			<li>您有權終止 Harry's Workspace 對您進行任何的資料蒐集，並得以要求 Harry's Workspace 刪除相關個人資料，唯其提供的服務將會受到相對限制，甚至是無法繼續提供您服務。</li>
		</ul>

		<h3>關於 Cookie/Cache 之運用：</h3>
        <p>沒在用，謝謝</p>

        <h3>其他：</h3>
		<p>對於您在本服務所登錄的個人資料及使用記錄，我們將採取適當步驟，盡最大努力確保資料儲存於本服務系統中的安全性。</p>
		<p>提醒您本服務不負責擔保網際網路資料傳輸之安全性，請您在使用前自行評估並判斷資料傳輸過程之中斷、流失、錯誤、被竊取、干擾等風險。</p>

		<h3>隱私權保護聲明的執行：</h3>
		<p>如果您對我們的隱私權保護聲明有任何問題，請與harry連絡。</p>
		<p>隱私權保護聲明的更新：本服務保留隨時修改本隱私權保護聲明的權利。修改後的條款將公佈於本服務網站上之相關網頁，並自公佈之日起生效，不另行通知。</p>
  </div>
</div>

app/views/home/test.html.erb
<svg>
<polygon fill="#68EADD" points="151,39 163,63 189,66 170,85 175,111 151,99 127,111 132,85
    113,66 139,63 "/>
</svg>

app/views/home/yeah.html.erb
<%= stylesheet_link_tag 'yeah' %>
<div class="container">
<div id="yeah"> <span> 耶 你找到秘密了～～ </span></div>
  <div class="confetti-149"></div>
  <div class="confetti-148"></div>
  <div class="confetti-147"></div>
  <div class="confetti-146"></div>
  <div class="confetti-145"></div>
  <div class="confetti-144"></div>
  <div class="confetti-143"></div>
  <div class="confetti-142"></div>
  <div class="confetti-141"></div>
  <div class="confetti-140"></div>
  <div class="confetti-139"></div>
  <div class="confetti-138"></div>
  <div class="confetti-137"></div>
  <div class="confetti-136"></div>
  <div class="confetti-135"></div>
  <div class="confetti-134"></div>
  <div class="confetti-133"></div>
  <div class="confetti-132"></div>
  <div class="confetti-131"></div>
  <div class="confetti-130"></div>
  <div class="confetti-129"></div>
  <div class="confetti-128"></div>
  <div class="confetti-127"></div>
  <div class="confetti-126"></div>
  <div class="confetti-125"></div>
  <div class="confetti-124"></div>
  <div class="confetti-123"></div>
  <div class="confetti-122"></div>
  <div class="confetti-121"></div>
  <div class="confetti-120"></div>
  <div class="confetti-119"></div>
  <div class="confetti-118"></div>
  <div class="confetti-117"></div>
  <div class="confetti-116"></div>
  <div class="confetti-115"></div>
  <div class="confetti-114"></div>
  <div class="confetti-113"></div>
  <div class="confetti-112"></div>
  <div class="confetti-111"></div>
  <div class="confetti-110"></div>
  <div class="confetti-109"></div>
  <div class="confetti-108"></div>
  <div class="confetti-107"></div>
  <div class="confetti-106"></div>
  <div class="confetti-105"></div>
  <div class="confetti-104"></div>
  <div class="confetti-103"></div>
  <div class="confetti-102"></div>
  <div class="confetti-101"></div>
  <div class="confetti-100"></div>
  <div class="confetti-99"></div>
  <div class="confetti-98"></div>
  <div class="confetti-97"></div>
  <div class="confetti-96"></div>
  <div class="confetti-95"></div>
  <div class="confetti-94"></div>
  <div class="confetti-93"></div>
  <div class="confetti-92"></div>
  <div class="confetti-91"></div>
  <div class="confetti-90"></div>
  <div class="confetti-89"></div>
  <div class="confetti-88"></div>
  <div class="confetti-87"></div>
  <div class="confetti-86"></div>
  <div class="confetti-85"></div>
  <div class="confetti-84"></div>
  <div class="confetti-83"></div>
  <div class="confetti-82"></div>
  <div class="confetti-81"></div>
  <div class="confetti-80"></div>
  <div class="confetti-79"></div>
  <div class="confetti-78"></div>
  <div class="confetti-77"></div>
  <div class="confetti-76"></div>
  <div class="confetti-75"></div>
  <div class="confetti-74"></div>
  <div class="confetti-73"></div>
  <div class="confetti-72"></div>
  <div class="confetti-71"></div>
  <div class="confetti-70"></div>
  <div class="confetti-69"></div>
  <div class="confetti-68"></div>
  <div class="confetti-67"></div>
  <div class="confetti-66"></div>
  <div class="confetti-65"></div>
  <div class="confetti-64"></div>
  <div class="confetti-63"></div>
  <div class="confetti-62"></div>
  <div class="confetti-61"></div>
  <div class="confetti-60"></div>
  <div class="confetti-59"></div>
  <div class="confetti-58"></div>
  <div class="confetti-57"></div>
  <div class="confetti-56"></div>
  <div class="confetti-55"></div>
  <div class="confetti-54"></div>
  <div class="confetti-53"></div>
  <div class="confetti-52"></div>
  <div class="confetti-51"></div>
  <div class="confetti-50"></div>
  <div class="confetti-49"></div>
  <div class="confetti-48"></div>
  <div class="confetti-47"></div>
  <div class="confetti-46"></div>
  <div class="confetti-45"></div>
  <div class="confetti-44"></div>
  <div class="confetti-43"></div>
  <div class="confetti-42"></div>
  <div class="confetti-41"></div>
  <div class="confetti-40"></div>
  <div class="confetti-39"></div>
  <div class="confetti-38"></div>
  <div class="confetti-37"></div>
  <div class="confetti-36"></div>
  <div class="confetti-35"></div>
  <div class="confetti-34"></div>
  <div class="confetti-33"></div>
  <div class="confetti-32"></div>
  <div class="confetti-31"></div>
  <div class="confetti-30"></div>
  <div class="confetti-29"></div>
  <div class="confetti-28"></div>
  <div class="confetti-27"></div>
  <div class="confetti-26"></div>
  <div class="confetti-25"></div>
  <div class="confetti-24"></div>
  <div class="confetti-23"></div>
  <div class="confetti-22"></div>
  <div class="confetti-21"></div>
  <div class="confetti-20"></div>
  <div class="confetti-19"></div>
  <div class="confetti-18"></div>
  <div class="confetti-17"></div>
  <div class="confetti-16"></div>
  <div class="confetti-15"></div>
  <div class="confetti-14"></div>
  <div class="confetti-13"></div>
  <div class="confetti-12"></div>
  <div class="confetti-11"></div>
  <div class="confetti-10"></div>
  <div class="confetti-9"></div>
  <div class="confetti-8"></div>
  <div class="confetti-7"></div>
  <div class="confetti-6"></div>
  <div class="confetti-5"></div>
  <div class="confetti-4"></div>
  <div class="confetti-3"></div>
  <div class="confetti-2"></div>
  <div class="confetti-1"></div>
  <div class="confetti-0"></div>

</div>