config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions:"users/sessions", registrations: "users/registrations" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'download', controller:'application', action:'download'
  get 'delete', controller:'application', action:'delete'
  post 'post_test', controller:'application', action:'post_test'
  get 'err', controller:'application', action:'err'
  get 'privacy_policy', controller: 'home', action: 'privacy_policy'
  post 'cancel_fb_authorization', controller: 'application', action: 'dev_cancel_fb'
  get 'google3e784468cd0fd9bb.html', controller: 'home', action: 'domain_auth'
  scope :controller=>"home",:path=>"/", :as=>"home" do
    get '/'=>:home
    get 'index'=>:index
    get 'about'=>:about
    get 'yeah'=>:yeah
    get 'test'=>:test
    post 'webhook'=>:webhook
  end

  resources :accounts, controller: 'accounts' do
    collection do
      get :index
      get :new
      post :add
      get :all
      get :show_day
      post :delete
      get :report
    end
  end

  resources :to_do_lists do
    resources :to_do_items do
      member do
        post :update_position
      end
    end
  end

  scope :controller => "excel", :path => "/excel", :as => "excel" do
    # get 'meetings/:id' => :show, :as => "meeting"
    get '/' => :index
    post '/upload' => :upload
    get '/show_csv' => :show_csv
    get '/processed_csv' => :processed_csv
    get '/export_filter_africa' => :export_filter_africa
  end

  scope :controller => "line", :path=> "/line", :as=>"line" do
    post '/webhook' => :webhook
  end

  resources :supplies, :controller=>'supplies' do
    collection do
      get '/all' => :all
    end
  end

  resources :articles do
    collection do
      get :search, to: redirect("/")
      post :search
      get :backup_settings
      post :backup
      get :mine
      post :preview_markdown
      get :hot
      get :cached_hot
      get :get_link_title
    end
    member do
      put :update_state
    end
  end

  resources :words, :controller=>'words'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/controllers/excel_controller.rb
class ExcelController < ApplicationController
  def index
    @uploads = []
    Dir.new(Global::CSV_UPLOAD_PATH).each do |file|
      if file.end_with?(".csv")
        @uploads.push(file)
      end
    end
    @uploads= @uploads.sort_by{|str| str.split('_')[0].to_i}

    @exports=[]
    check_exports
    Dir.new(Global::CSV_EXPORT_PATH).each do |file|
      if file.end_with?(".csv")
        @exports.push(file)
      end
    end
    @exports = @exports.sort_by{|str| str.split('_')[0].to_i}
  end

  def upload
    uploaded_io = params[:csv_file]
    @uploads = []
    Dir.new(Global::CSV_UPLOAD_PATH).each do |file|
      if file.end_with?(".csv")
        @uploads.push(file)
      end
    end
    begin
      File.open(Rails.root.join(Global::CSV_UPLOAD_PATH, @uploads.size.to_s+"_"+uploaded_io.original_filename.gsub(' ','_')), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      puts("Uploaded "+uploaded_io.original_filename)
      redirect_to action:'index'
    rescue=>exception
      puts(exception)
    end
  end

  def show_csv
    begin
      @file_name = params[:file_io]
      @file_path = get_full_csv_path @file_name
      @hash_arr = read_hash_from @file_name, false
      @longest_hash = @hash_arr.max_by(&:length)
      # @hash_arr = @hash_arr.delete_if{|hash| hash[:country]=="Papua New Guinea" } 這是array of hash 可以用
      @hash_arr = @hash_arr.delete_if{|hash| hash["country"]=="Papua New Guinea"}
    rescue=>exception
      flash[:alert] = exception.to_s
      render 'shared/result',locals:{status:false, message:"抱歉，把下面的貼給我",error: exception.to_s}
    end
  end

  def processed_csv
    # begin
    @file_name = params[:file_io]
    @hash_arr = read_hash_from @file_name, false
    @africa = africa_arr
    @matched = filter_af @hash_arr
    @longest_hash = @matched.max_by(&:length)
    @missing = find_missing @matched
    @matched = fill_empty @matched
    @matched = @matched.sort_by{|hash| hash["country_code"]}
    # rescue=>exception
    #   flash[:alert] = exception.to_s
    #   render 'shared/result',locals:{status:false, message:"抱歉，把下面的貼給我",error: exception.to_s}
    # end
  end

  def export_filter_africa
    # begin
    @file_name = params[:file_io]
    @hash_arr = read_hash_from @file_name, false
    @africa = africa_arr
    @matched = filter_af @hash_arr
    @longest_hash = @matched.max_by(&:length)

    @matched = fill_empty @matched

    @matched = @matched.sort_by{|hash| hash["country_code"]}
    filename = export_africa @matched, params[:file_io]
    flash[:notice] = "成功輸出了 #{filename}"
    redirect_to action:'index'
    # rescue=>exception
      # return render 'shared/result',locals:{status:false, message:"抱歉他怪怪的，把下面的貼給我",error: exception.to_s}
    # end
  end

  def filter_af hash_arr
    final_arr = []
    hash_arr.each do |hash|
      africa_arr().each do |countryItem|
        if /#{countryItem[0]}/.match(hash["country"])
          hash["country_code"] = countryItem[1]
          new_hash = {:no=>countryItem[2]}.merge(hash)
          final_arr.push(new_hash)
          break
        end
      end
    end
    final_arr = final_arr.delete_if{|hash| hash["country"]=="Papua New Guinea" }
    return final_arr
  end

  def find_missing hash_arr
    recording = Hash.new
    missing = []
    africa_arr().each do |pair|
      recording["#{pair[1]}"] = false
    end
    hash_arr.each do |hash|
      recording["#{hash["country_code"]}"]=true
    end
    africa_hashes = africa_arr().map{
      |e|
      [e[0],e[1]]
    }.to_h.invert
    recording.each do |k,v|
      if !v
        missing.push(africa_hashes["#{k}"].gsub('.*',' '))
      end
    end
    # puts '============================'
    # puts missing
    # puts '============================'
    return missing.sort
  end

  def fill_empty hash_arr
    current_codes = hash_arr.map{|hash| hash["country_code"]}
    africa_arr().each do |e|
      if current_codes.exclude?(e[1])
        hash = {"no"=>e[2], "country"=>e[0].gsub('.*',' '), "country_code"=>e[1],"empty"=>"這個資料沒有這個國家"}
        hash_arr.push(hash)
        puts hash
      end
    end
    return hash_arr
  end

  def africa_arr
    [ ["Angola","AGO",1],
      ["Burundi","BDI",2],
      ["Benin","BEN",3],
      ["Burkina.*Faso","BFA",4],
      ["Botswana","BWA",5],
      ["Central.*African.*Republic","CAF",6],
      ["Ivoire","CIV",7],
      ["Cameroon","CMR",8],
      [".*Congo.*Dem.*","COD",9],
      ["Congo","COG",10],
      ["Comoros","COM",11],
      ["Cape.*Verde","CPV",12],
      ["Djibouti","DJI",13],
      ["Algeria","DZA",14],
      ["Egypt","EGY",15],
      ["Eritrea","ERI",16],
      ["Ethiopia","ETH",17],
      ["Gabon","GAB",18],
      ["Ghana","GHA",19],
      ["Guinea","GIN",20],
      ["Gambia","GMB",21],
      ["Guinea.*Bissau","GNB",22],
      ["Equatorial.*Guinea","GNQ",23],
      ["Kenya","KEN",24],
      ["Liberia","LBR",25],
      ["Libya","LBY",26],
      ["Lesotho","LSO",27],
      ["Morocco","MAR",28],
      ["Madagascar","MDG",28],
      ["Mali","MLI",30],
      ["Mozambique","MOZ",31],
      ["Mauritania","MRT",32],
      ["Mauritius","MUS",33],
      ["Malawi","MWI",34],
      ["Namibia","NAM",35],
      ["Niger","NER",36],
      ["Nigeria","NGA",37],
      ["Rwanda","RWA",38],
      ["Sudan","SDN",39],
      ["Senegal","SEN",40],
      ["Sierra.*Leone","SLE",41],
      ["Somalia","SOM",42],
      ["South.*Sudan","SSD",43],
      [".*Sao.*Tome.*Principe.*","STP",44],
      ["Swaziland","SWZ",45],
      ["Eswatini","SWZ",45],
      ["Seychelles","SYC",46],
      ["Chad","TCD",47],
      ["Togo","TGO",48],
      ["Tunisia","TUN",49],
      ["Tanzania","TZA",50],
      ["Uganda","UGA",51],
      ["South.*Africa","ZAF",52],
      ["Zambia","ZMB",53],
      ["Zimbabwe","ZWE",54]
    ].sort_by{|element| element[0].length}.reverse
  end
end

app/views/excel/index.html.erb
<div id="container-excel">
   <h1>Excel</h1>
  <div id="form-upload">
    <%= form_tag(excel_upload_path, method:"post",:multipart => true) %>
    <%= label_tag '檔案'%>
    <%= file_field_tag :csv_file,class:"file-input" %>
    <%= button_tag '送出', class:'input btn-excel'%>
  </div>
  <div id="wrap-two-tables">
   <div id="wrap-table">
   <h2>Uploaded</h2>
      <% if @uploads.size==0 %>
        <h4>Nothing，呢呢</h4>
      <% else %>
        <table class="table-file">
          <thead>
            <tr>
              <th class="file-icon">Download</th>
              <th class="file-name">Name</th>
              <th class="file-delete">Delete</th>
            </tr>
          </thead>
          <tbody>
              <% @uploads.each do |path|  %>
              <tr>
                <td class="file-icon">
                  <%= link_to("#{image_tag("excel.png",class:"path-icon") }".html_safe, download_path(file_path:Rails.root.join(Global::CSV_UPLOAD_PATH, path)),class:"") %>
                </td>
                <td class="file-name">
                  <%= link_to(path.split('/')[-1], excel_show_csv_path(file_io:path)) %>
                </td>
                <td class="file-delete wrap-delete">
                  <%= link_to(content_tag(:div, "X",class:"delete-icon"),delete_path(file_path:Rails.root.join(Global::CSV_UPLOAD_PATH, path)),data:{confirm:"真的要刪掉#{path}嗎?"}) %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>
    <% end %>
   </div>

   <div class="wrap-table">
     <h2>Output</h2>
      <% if @exports.size==0 %>
        <h4>Nothing，呢呢</h4>
      <% else %>
        <table class="table-file">
            <thead>
              <tr>
                <th class="file-icon">Download</th>
                <th class="file-name">Name</th>
                <th class="file-delete">Delete</th>
              </tr>
            </thead>
            <tbody>
                <% @exports.each do |path|  %>
                <tr class="tr-data">
                  <td class="file-icon">
                    <%= link_to("#{image_tag("excel.png",class:"path-icon") }".html_safe, download_path(file_path:Rails.root.join(Global::CSV_EXPORT_PATH, path)),class:"") %>
                  </td>
                  <td class="file-name">
                    <%= link_to(path.split('/')[-1], excel_show_csv_path(file_io:path)) %>
                  </td>
                  <td class="file-delete wrap-delete">
                     <%= link_to(content_tag(:div, "X",class:"delete-icon"),delete_path(file_path:Rails.root.join(Global::CSV_EXPORT_PATH, path)),data:{confirm:"真的要刪掉#{path}嗎?"}) %>
                  </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>

   </div>
  </div>
</div>

app/views/excel/processed_csv.html.erb
<div id="container-cl">
  <h1> <%= (@hash_arr.size>0? "✅":  "❌") %>  處理結果 </h1>
  <div style="margin-left:20px;">
    <table class="table-info">
      <tr>
        <td>檔案名稱</td><td><%= @file_name %></td>
      </tr>
      <tr>
        <td>檔案列數</td><td><%= @hash_arr.size %> 列</td>
      </tr>
      <tr>
        <td>內含非洲</td><td><%= @matched.size %>筆</td>
      </tr>
      <tr>
        <%# -1 是因 為了找Swaziland = Eswatini%>
        <td>hazel提供的非洲表</td><td><%= @africa.size-1 %>個國家</td>
      </tr>
       <tr>
        <td class="<%(@missing.size>0? '': "missing")%>">缺少</td><td class="<%(@missing.size>0? '': "missing")%>"><%= @missing.size %>個國家</td>
      </tr>
    </table>
       <%# Missing table %>
     <% if @missing.size>0 %>
    <hr>
      <table class="table-info">
        <% @missing.each do |country| %>
          <tr>
            <td class="missing"> 沒有 </td><td class="missing"> <%= country %> </td>
          </tr>
        <%end%>
      </table>
     <% end %>
  </div>

  <% if @matched.size>0 %>
    <%= link_to("輸出",excel_export_filter_africa_path(file_io:@file_name),class:"btn-export") %>
    <div class="wrap-excel">
      <%# <h1>以下沒有</h1>
      <table class="table-excel table2">
             <thead>
               <tr>
                 <th>國家</th>
               </tr>
             </thead>
             <tbody> %>
               <%# <% @missings.each do |country|%>
                 <%# <tr> %>
                   <%# <td><%= country</td>  %>
                 <%# </tr> %>
               <%# <% end %>
             <%# </tbody> %>
      <%# </table> %>

      <%# <hr> %>

      <table class="table-excel processed-excel">
        <thead>
          <tr>
              <% @longest_hash.each do |hash_arr| %>
                <th> <%= hash_arr[0] %></th>
              <%end%>
          </tr>
        </thead>
        <tbody>
          <% @matched.each do |row| %>
            <tr>
              <% row.each do |hash_arr| %>
                <td> <%= hash_arr[1] %></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
   <% else %>
     <h3>呢呢，裡面沒東西</h3>
   <% end %>

</div>

app/views/excel/show_csv.html.erb
<div id="container-cl">
  <h1><%= link_to("← 上一頁",excel_path,class:"back") %></h1>
  <h1>預覽</h1>
  <div style="margin-left:20px;">
    <table class="table-info">
    <tr>
      <td>檔案名稱：</td> <td><%= @file_name %></td>
    </tr>
    <tr>
      <td>資料表共：</td> <td><%= @hash_arr.size %> 列</td>
    </tr>
    <tr>
      <td>下載</td> <td><%= link_to(image_tag("excel.png",style:"height:30px;withe:30px;"),download_path(file_path: @file_path)) %></td>
    </tr>
    </table>
  </div>

  <% if @hash_arr.size>0 %>
    <%= link_to("過濾非洲",excel_processed_csv_path(file_io:@file_name),class:"btn-export") %>
  <% else %>
    <%= button_tag("不能處理","#",class:"btn-report") %>
  <% end %>

  <div class="wrap-excel">
    <table class="table-excel show-excel">
      <thead>
        <tr>
          <% begin %>
              <% @longest_hash.each do |hash_arr| %>
                <th> <%= hash_arr[0] %></th>
              <%end%>
            <% rescue=>exception %>
             <%= @hash_arr %>
            <% end %>
        </tr>
      </thead>
      <tbody>
        <% @hash_arr.each do |row| %>
          <tr>
            <% begin %>
              <% row.each do |hash_arr| %>
                <td> <%= hash_arr[1] %></td>
              <%end%>
            <% rescue=>exception %>
              <%= @hash_arr %>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>